{{- range .Values.secrets }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  fields:
    {{- range .fields }}
    - fieldName: {{ .fieldName }}
      length: {{ .length | default "32" | quote }}
      {{- with .encoding }}
      encoding: {{ . }}
      {{- end }}
    {{- end }}
{{- end }}
